== Overview

=== Scope

This report describes the preliminary approach for the Spatial Web UDG System Design Specification.  

NOTE: In IEEE 2874-2025 this document was titled the UDG Implmentation Specification.

=== Purpose

The purpose of this report is to provide information that is relevant to a Spatial Web UDG design. The UDG design in this report defines requirements for the Spatial Web Implementation standards and guides domain-specific Spatial Web architecture development.

=== Structure of document

The report addresses these themes:

* Identifies requirements and fundamental design questions
* Provides an assessment of relevant, existing technology and research
* Defines UDG system design, including foundations, conceptual models and distributed computing

This document is structured as an architecture description consistent with the approach defined in <<ISO_IEC_IEEE_42010_2022, Spatial Web Protocol, Architecture and Governance>>. 

This document provides five viewpoints of the UDG.  These viewpoints comprise the UDG system design:

* <<section-enterprise-viewpoint, Enterprise viewpoint>>
* <<section-conceptual-view-knowldge-graph, UDG as a knowledge graph>>
* <<section-conceptual-view-hyperspace, UDG hyperspace atlas>>
* <<section-conceptual-registry, UDG as a registry of registries>>
* <<section-conceputal-view-social-network, UDG as a social network>>
* <<section-distributed-computing, UDG distributed computing>>


=== Conventions used in this standard

In this document the following Spatial Web ontology entries (ENTITY, ACTIVITY, AGENT, CONTRACT, CHANNEL, CREDENTIAL, DOMAIN, HYPERSPACE, and TIME) are represented using uppercase.
