== Terms, definitions and abbreviated terms

=== Terms and definitions


==== artificial intelligence

preferred:[AI]

The capacity of computers or other machines to exhibit or simulate intelligent behavior.

[.source]
<<IEEE_7010_2020>>

==== distributed computing

Model of computing in which a set of nodes coordinates its activities by means of digital messages passed between the nodes.

[.source]
<<ISO_IEC_23188_2020,clause=3.1.1>>

// rwp 2025-11 revised definition; i think this needs more consideration; 
// 2d and 3d could be considered a dimension by some people; 
// perhaps this is a measureable dimension;
// is this related to a coordinate dimension/extent?

==== dimension

A kind of measurable extent.

[example]
Length, breadth, depth, or height are examples of dimension. 


==== DOMAIN

Sphere of knowledge, influence, or ACTIVITY.

related:seealso[ENTITY]

[.source]
<<IEEE_2874_2025,clause=3>>


==== domain authority

An ENTITY that is CREDENTIALED to have the ability to define within a DOMAIN the norms and terms under which CONTRACTS are created governing: AGENTS, ACTIVITIES and CREDENTIALS within that DOMAIN.

[.source]
<<IEEE_2874_2025,clause=3>>

==== ENTITY

that which is perceived, known, or inferred to exist, has existed, or is anticipated to exist.

[example]
An event, idea, object, person, process, etc.

NOTE: An ENTITY can exist whether data about it are available or not.

NOTE: ENTITY is the base item in the Spatial Web Ontology. 

// <<section-hsml-conceptual-model>>

[.source]
<<IEEE_2874_2025,clause=3>>


// rwp 2025-11: switching with 2874-2025 definition
// A type of vector space in which the notions of distance and angle are defined.

==== Euclidean space

Real vector space or real point space for which a scalar product is defined for any two vectors.

NOTE: The usual geometrical three-dimensional space is a Euclidean point space. Four-dimensional vectors used in special relativity are elements of a non-Euclidean point space because the scalar product of a vector by itself may be negative.

NOTE: Euclidean space is a type of vector space.

[.source]
<<ievterms_m,clause=02-03-19>>, Note 1 has been modified. Note 2 has been added.



// rwp 2025-11 what is a "generalized CRS"?
==== Generalized worlds

ENTITIES embedded in a vector class of HYPERSPACE using a generalized coordinate reference system to define location in a high dimensional space.

NOTE: Generalized worlds are a generalization of geographic information referenced to a geographic coordinate reference system.

NOTE: see also World2Vec

NOTE: the term "generalized worlds" may be changed, but the concept as defined in <<generalized-worlds>> needs to be defined and given a stable term.

==== geographic coordinate reference system

Coordinate reference system that has a geodetic reference frame and an ellipsoidal coordinate system.

[.source]
<<ISO_19111_2019,clause=3.1.35>>


==== graph space

A set of nodes and edges such that every edge has both a source node and a target node.

NOTE: Graph space is a type of {{HYPERSPACE}}.

// rwp 2025-11: differs from IEEE 2874-2025 definition

==== HYPERSPACE

preferred:[SPACE]

A set of 'points' such that, for every ordered pair of points, there is a possibly empty set of 'paths' from the first point to the second, and such that there is an 'identity' path from every point to itself.

==== Hyperspace Modelling Language
preferred:[HSML]

[%metadata]
abbreviation-type:: initialism

A human- and machine-readable modeling language and semantic data ontology schema that describes objects, relations, actions, activities and their permissions.

NOTE: Uses of {{HSML}} include the expression and automated execution of legal, financial, and physical activities.

[.source]
<<IEEE_2874_2025,clause=3>>

==== Hyperspace Transaction Protocol
preferred:[HSTP]

[%metadata]
abbreviation-type:: initialism

Generic protocol designed to underwrite automated contracting transactions that are required for building a coherent, decentralized, secure, and privacy-respecting {{Spatial Web}}.

[.source]
<<IEEE_2874_2025,clause=3>>

==== register

Set of files containing identifiers assigned to items with descriptions of the associated items

[.source]
<<ISO_19135_1_2015,clause=4.1.9>>

// rwp 2025-11: is quite broad and seems more like an example; 
// must consider this more

==== relationship

Links, portals, membership, situations, paths


// 2025-11 ISO_IEC_IEEE_24765_2017 provides a definition of representation as:
// 3.3418
// representation
// 1. logical portrayal of a physical, operational, or conceptual image or situation 2. one or more properties used by an algorithm for the realization of a responsibility [IEEE 1320.2-1998 (R2004) IEEE Standard for Conceptual Modeling Language Syntax and Semantics for IDEF1X97 (IDEFobject), 3.1.162]

// but this seems different

// original definition in UDG
// Model that can be used to describe some aspect of a world.
// modified 2025-11 rwp

==== representation

Model used to describe some aspect of a world.

NOTE: Representations can be passive or active. A passive representation reflects a possible state of affairs, typically the state of a spatio-temporal local slice of an AGENT'S environment, while an active representation changes the state of a system to conform to the representation.

NOTE: Representations can be probabilistic such as conditional probability distributions or Bayesian beliefs. They can describe either state of the world that generates data or content, at a particular moment in time, or the contingencies and dynamics that could depend upon the actions of a user.


==== Spatial Web

Network structures supported by the protocol, architecture, and governance related to {{HSTP}} and {{HSML}} and their supporting components.

[.source]
<<IEEE_2874_2025,clause=3>>


// rwp 2025-11: differs from IEEE 2874-2025 definition

==== spatial web identifier
preferred:[SWID]

A decentralized identifier used to uniquely identify an ENTITY, DOMAIN, or other item within the {{Spatial Web}}.

==== Spatial Web Domain Server

Networked server that provides location-based identification of HYPERSPACE assets and ownership information to Spatial Web Domains.

NOTE: A Spatial Web Domain Server handles spatial content retrieval and spatial transaction validation, whereby the rules for particular areas can be described as spatial permissions in their associated assets.

[.source]
<<IEEE_2874_2025,clause=3>>


==== Spatial Web Node

Computing machine connected to the internet, capable of exchanging {{HSTP}} messages.

[.source]
<<IEEE_2874_2025,clause=3>>


==== universal domain graph
preferred:[UDG]

A distributed hypergraph which contains all relationships between all known {{SWID,SWIDs}} in the Spatial Web.

NOTE:  The universal domain graph is the complete {{Spatial Web,Spatial Web}} hypergraph.

[.source]
<<IEEE_2874_2025,clause=3>>


==== distributed universal domain graph system
preferred:[distributed UDG system]

The set of coordinated Spatial Web Nodes that provide services on the distributed UDG.

[.source]
<<IEEE_2874_2025,clause=3>>

// rwp 2025-11: should SW entities be SW ENTITIES (caps)?

==== UDG entity graph

All instances of SW entities and connections represented in {{HSML}}



==== UDG node graph:

All distributed computing {{Spatial Web Node, Spatial Web Nodes}} and connections using {{HSTP}}


// rwp 2025-11: is this a note? or author memo? 
// Compare with Spatial Web Domain Server

==== UDG Node

A type of distributed computing {{Spatial Web Node}} that performs UDG functions


==== vector space

Type of space composed of {{dimension,dimensions}} where each {{dimension}} is the set of real numbers.

NOTE: Vector space is a type of {{HYPERSPACE}}, and {{Euclidean space}} is a type of vector space.

[.source]
<<IEEE_2874_2025,clause=3>>


// rwp 2025-11 continue to check if these are presently used in the document or not

=== Abbreviated terms

AI:: artificial intelligence
API:: application programming interface
AR:: augmented reality
// BFO:: basic formal ontology
CRS:: coordinate reference system
// CRUD:: create, read, update, and delete
DGGS:: Discrete Global Grid System
DLT:: distributed ledger technology
// FAIR:: Findable, Accessible, Interoperable, and Reusable
// glTF:: GL Transmission Format
// IIC:: Industry IoT Consortium
IoT:: Internet of Things
IRI:: Internationalized Resource Identifier
// M2M:: machine to machine
// MIME:: Multipurpose Internet Mail Extensions
// OGC:: Open Geospatial Consortium
// OWL:: Web Ontology Language
RDF:: Resource Description Framework
SHACL:: Shapes Constraint Language
// SKOS:: Simple Knowledge Organization System
SPARQL:: SPARQL Protocol and RDF Query Language
// SWE:: Sensor Web Enablement
UDG:: Universal Domain Graph
// UDT:: Urban Digital Twin
// VC:: verifiable credentials
// VR:: virtual reality
W3C:: World Wide Web Consortium
// WoT:: Web of Things
XR:: collective reference to both AR and VR
// ZKP:: zero-knowledge proof

