[[domain-entity-type]]
== Domain Types

A DOMAIN type is a specialization of an entity that incorporates additional
capabilities. Within the Spatial Web, these extensions are defined using the
Shape Constraint Language (SHACL), as a generalized schema language, with the
mechanism for such extension covered in this section.

Currently several DOMAIN types are defined: Place, Link, Domain, Sensor, Thing, Agent, and Assemblages, with others derivable from these. These are differentiated as follows:

* A __place__ is defined roughly as a specific addressable location within a domain. Places define where an entity can be, and where they can't. Cf <<places,Places>> for more information.

* A __link__ is a mechanism for navigating between both places (internal links) and domains (external links). It is the analog of a hypertext link in the HTTP world.Cf. <<links,Links>> for more information.

* A __domain__ is a system of concern, and is effectively the partition of a given universe into a navigable area. Domains are where things happen. Cf <<domains,Domains>>.

* A __sensor__ is an abstraction of a camera, recording device, eyeball, etc. Its purpose is to provide a reference point of view for an entity within a domain (or of the domain itself).  Cf. <<sensors,Sensors>> for more information.

* A __thing__ is defined as an entity that is directed by the system (the local spatial web daemon). Not that directed here means simply that it provides the motivating influence on the thing, not that it determines a things exact behaviors. In effect, both things and agents are "semi-autonomous" in that they have some (perhaps minimal) self-control, but they respond to outside influences. Things can be considered non-player characters, but they can also be structures, vehicles, animals, portals, and so forth. Cf. link:#things[Things] for more details.

* An __agent__ is defined as an entity that is directable by an outside (out of system) actor. Agents generally act as the eyes, ears, hands, and feet of the actor. It corresponds roughly to a character in a novel, play, or game, but in a more generalized fashion. Cf. <<agents,Agents>> for more details.

* An __assemblage__ is an aggregate structure of things, places, and agents. It is intended to model corporations, institutions, governments, and so forth, but it can also model physical or other composite structures.  Cf. link:#assemblages[Assemblages] for more information.