[[section-conceptual-view-knowldge-graph]]
== UDG as a knowledge graph

=== Knowledge Graphs

This clause considers the UDG as a knowledge graph (KG). A KG is a representation of information that uses a graph-structured data model to represent and operate on data <<wikipedia-KG>>. 

The UDG KG is a graph where the nodes are Spatial Web ENTITIES. Interlinking of ENTITIES in the UDG is accomplished using Links, portals, membership, situations, paths (see <<relationships>>).

Knowledge in the Spatial Web will include statements of fact as well as statements with probablistic uncertainty. At any given time contradictory statements will exist unresovled across the UDG KG.  Statements of knowledge will change through the dialectic activity of social agents as defined in <<section-conceptual-view-social-network>>.

Messages between nodes in the UDG KG comply with HSML specification. The HSML builds upon the W3C Resource Description Framework (RDF) suite of standards. RDF graphs are sets of subject-predicate-object triples, where the elements may be IRIs, blank nodes, datatyped literals, or triple terms. 

include::05-02-domain.adoc[leveloffset=+2]

include::05-03-links-membership.adoc[leveloffset=+2]

include::05-04-udg-taxonomy.adoc[leveloffset=+2]

include::05-05-use-cases.adoc[leveloffset=+2]