= Hyperspace geography applications

== Geospatial and graph domains for urban energy grid

The Urban digital twin / Smart city applciation scenario <<IEEE_2874_2025, Spatial Web clause 5.3.7>> shows how the Spatial Web enables digital twin technology for addressing urban sustainability with a focus on energy. Using urban energy system modeling and analysis developed in the Spatial Web multi-scale cognitive computing ecosystem will benefit next generation cities and the globe. Considering climate change it is vital that more cities deploy energy UDTs to address energy consumption and climate sustainability.  

<<IEEE_2874_2025, Spatial Web clause 6.3.7>> defines DOMAINS required for the energy scenario.  

* The Metropolis Digital Twin DOMAIN provides the geometry for the Metropolis using vector space. The Metropolis Digital Twin domain is a geographic Domain. Domain [metropolis] is all regions near the surface of the Earth that are managed by the Metropolis government.
* The Regional Energy Grid DOMAIN defines the connectivity of nodes in the energy grid using a graph space. The Regional Energy Grid Domain is a conceptual graph or knowledge base for the concepts and operations of a regional energy grid.
* The Metropolis Digital Twin—​Energy Model DOMAIN aims to provide a common interface on the Metropolis space model and the Energy grid graph model.  The Metropolis Digital Twin—​Energy Model Domain is holonically related to the Metropolis Digital Twin Domain and the Regional Energy Grid domain.

== Improving KGs using geospatial features

Integration of geospatial features into knowledge graphs can enable more precise characterization of knowledge dynamics across temporal and geographic dimensions.. The absence of geospatial information significantly undermines the value of such knowledge representations. Spatial embedding can coordinate relational semantics with spatial-temporal geography models.  A geometry-aware embedding space that dynamically fuses spatial grids and temporal slices through spatio-temporal states, enables robust reasoning on heterogeneous graphs <<stse>>.


== Global Earth observation models

Massive Earth Observation (EO) archives containing hundreds of petabytes of dataoffer a huge potential for understanding the Earth’s resources and potential hazards tosecurity while also addressing societal challenges <<Element_84>>. There is a growing need for efficient vector representations of the underlying raw data. The approach of extracting feature representations from pretrained deep neural networks is a powerful approach that can provide semantic abstractions of the input data. Several projects are creating global and dense embedding datasets released openly and for free. <<Embeddings_of_Earth>>, <<AlphaEarth>>.

== Telecoupling

Telecoupling implicilty uses hyperspace for identifying connections between physically distant systems.  Telecoupling exposes socioeconomic and environmental interactions between distant coupled human and natural systems. The integrated framework of telecoupling examines flows of information, energy, matter, people, organisms, and other things such as financial capital and goods and products around the globe. It pinpoints causes and effects arising from engagement of diverse agents in the global sphere.  It enables recognizing trade-offs between local and global sustainability and the need for multi-level management and governance solutions.  Telecoupling can help systematically expand from a focus on specific places separately to human-nature interactions across distant places.  (see <<Hull_and_Liu>> and <<Manning>>)


== Emboddied cyber-physical agents

Living systems balance energetic efficiency with the capacity for path-dependent effects. <<blattner>> defines a geometric framework that models embodied agents as hierarchies of manifolds linked by projections from physical states to cognitive representations and onward to intentions. The framework consists of three manifolds/subspaces - Physical, Cognitive, Intentional - along with functions for mapping between the spaces; mappings which constrain the paths in each space. The framework provides a geometric language linking embodiment, memory, and energetic cost, yielding testable predictions and design guidelines for biological and robotic systems. This framework might provide necessary rules for structures in the UDG which could be utilized for desired UDG-based behaviors of cyber-physical agents,


== Active inference for collective intelligence

Ecosystems of intelligence are core to the Spatial Web. Intelligence can be understood as the capacity to accumulate evidence for a generative model of a sensed world. Formally, this corresponds to maximizing model evidence, via belief updating over several scales: i.e., inference, learning, and model selection Friston et al. <<Ecosystems_intelligence>>. Operationally, this self-evidencing can be realized via message passing or belief propagation on a factor graph. This same imperative underwrites belief sharing in ensembles of agents, in which certain aspects of each agent’s generative world model provide a common ground or frame of reference. Active inference addresses this ecology of belief sharing—leading to a formal account of collective intelligence that rests on shared narratives and goals. Based on this perspective, levels of multi-scale cognitive computing in a Spatial Web ecosystem of Agents can be defined. The ensuing levels can be used for governance in the Spatial Web.


