= Social Agents

EDITOR: STD-1 generalized the MLB example to a generic baseball league.  

== TBD

* Social agents: agent based networks
** UDG Nodes shall conduct sociometric data on agent interactions
* Group sizes: situation, cluster, society
* Social signaling


- [ ] Model from agent framework
- [ ] Paradise: Ensemble Social Physics with LLM
- [ ] Natural Curiosity, Nagel, 2024
  Curiosity is an intrinsic desire for knowledge. This raises a puzzle about how unreflective animals can be curious. It is easy to understand how learning could be driven by factors such as hunger, but what proximal signal could guide animals towards knowledge itself? Recent work in reinforcement learning suggests that surprise functions as a reward signal for the curious animal. Reward for surprise can then be shown to amount to a desire for knowledge gain, where knowledge is a cognitive adaptation to reality. This adaptation results in a mental state whose stable existence depends essentially on the truth of its contents; that is, a factive mental state. Curious creatures benefit from an interaction between the prediction-error correction processes of basic learning and the active surprise-seeking force of their curiosity. This internally adversarial interaction accelerates knowledge gain in ways that are helpful for biological creatures in a complex natural world.
 - Friston, Karl & Lin, Marco & Frith, Chris & Pezzulo, Giovanni & Hobson, J. & Ondobaka, Sasha. (2017). Active Inference, Curiosity and Insight. Neural Computation. 29. 2633-2683. 10.1162/neco_a_00999. 
     In short, the simulations used to illustrate the emergence of curiosity and insight below follow from a single principle: the minimization of free energy (i.e., surprise) or maximization of model evidence.
- Veissière SPL, Constant A, Ramstead MJD, Friston KJ, Kirmayer LJ. Thinking through other minds: A variational approach to cognition and culture. Behavioral and Brain Sciences. 2020;43:e90. doi:10.1017/S0140525X19001213
  Intrinsic motivation and artificial curiosity enable the agent toexplore novel, transient, and unexpected regions of the space ofpolicies open to them. This can be an “adaptive” exploration orepistemic foraging, because it allows for the exploration of thisspace; over longer timescales, the local increase in free energyserves the more general process of reducing free energy (for eitherthe individual or the group, because it prepares the organism forpotential changes in adaptive contexts and enlarges the repertoireof responses for the individual or the group). S
- [ ] Agents are not Enough
- [ ] Decision Theory in Multi-Agent Systems, Ki, Soh, 2004

[[sensors]]
== Sensors 
The challenge that is faced with the Spatial Web is that what you see is not always what you get. In general, the way that a given domain is perceived will vary depending upon the observer - some observers will be capable of seeing a great deal, others, not much at all. In order to manage this, one particularly useful entity is the *__sensor__*.

> A __sensor__ is a mechanism to get a particular point of view on a domain from the perspective of either a place, agent, assemblage or thing.

The most obvious form of sensor is an _eyeball_, or the mechanical equivalent, the _camera_. However, this gives a fairly restrictive idea about what sensors are capable of.

As an example, a very common sensor is a map-view sensor, which provides a representation of a particular domain from the perspective of an all encompassing eye (the map-view, or omniscient-view). This need not be a direct satellite view, but instead may be some form of boundary heat map drawing or icon view of entities within the domain. This may also generate an ESRI shape file, KML, GeoJSON, Geographic Markup Language, OSM, IDRISI Vectors, or similar format map resources.

Similarly, a sensor may be a game-view, which shows the places in a game map with pieces (agents) located within those places. For instance, the game of RISK would generate such a game view that would be similar to a "standard" RISK board.

Sensors are also not just visual. A sensor may provide a written or verbal description, data files, audio, image or video renditions and ao forth. The idea behind this is essential that a sensor provides information from multiple potential perspectives, across multiple filters, to generate multiple formats.

Sensors ask sensory information about a thing or environment, and most specifically are used to answer the question? What is a description of this thing?

Sensors are typically attached to an entity, with a single entity having multiple potential sensors (also known as a __sensor array__).

Every entity has a state description graph, also known as a hyperspace represented as an n-dimensional hypercube (likely implemented as a W3C datacube). This represents the broadcast or public properties or features of the entity. The sensor array acts as a filter to perceive specific properties and interpret them.

Sensors are basically data plugins - they are intended to provide some meaningful mapping of information coming from the entity state description graph and make that available in a consistent fashion.

The exact mechanism for how sensors work is still under development, but runs roughly along the following lines:

[source,mermaid]
----

---
config:
    layout: elk
---
graph TD
    start([start])-->hstpReq[HSTP requests<br>View]
    hstpReq-->iterate[Agent iterates<br>through other<br>entities' states]
    iterate --> filter[Filter through<br>known sensor<br>Filters]
    filter --> transform[Transform the<br>result into<br>requested format]
    transform --> respond[Send to<br>output channel]
    respond-->stop
----
In general, this output is performed as an HSTP request to get a description of state of either a given entity or the domain of entities.

A similar loop occurs for each entity's internal update, but does not include the filter or transform, and typically does not respond to data outside of the hsml namespace. This is used in order to query the state of the surrounding graph in order to adjust movement to desired goals. This is handled by the internal udg daemon.
