= SW Node Registries

== SW Nodes

A Spatial Web Node (or SW Node) is a daemon on a computer server that host
Spatial Web KG entities. It is roughly analogous to an http.d daemon that hosts
a web contnet, and typically hosts a *__domain graph__* that maintains the state
of multiple ENTITIES, DOMAINS, CREDENTIALS, CONTRACTS and related content.

== SW Node Networks

A SW Node communicates with other SW Nodes via HSTP. SW Nodes connect in one of
two ways:

. Via __neighborhood connections__ made when the node connects via a nodelink (a
specialized form of link that identifies a node) to another node. The successful
negotiation caches the nodelink in the node's __nodecache__. This is a
peer-to-peer connection.

. Via registration with a __public node registry__. In this case, the node
becomes visible to all other members of the registry. The registration process
returns a set of credentials that translate selected links from a search into
neighborhood links.

In both cases, when a node queries another node about its neighborhood, it can
cache the connections of the queried node. Case 2 in fact is essentially
Case 1 at a larger scale. Each node contains a certain amount of intrinsic
metadata about the type of domains on the system, which can in turn be used to
provide a facet query to find links from another node that have similar or
overlapping facets.

For instance, if a given node mostly contained shipping information, the facets
that it has can provide scores against another SW Node's registry metadata that
was tied into shipping to retrieve those particular SW Nodes that are most like
the requested nodes.

In addition to that, when a Spatial Web Node first registers with a registry, it
can retrieve schema definitions, common resources, code libraries and a
"starter" set of node links that can then be used to add to the neighborhood of
the registering node.

Nodelinks typically have a time-to-live attribute (TTL) that indicates how long
a link can remain active before it needs to be refreshed. If a nodelink cannot
be resolved, then a secondary TTL is activated that indicates how long an
interval should be taken before the link is considered dead, and consequently
should be purged.

== Discovery

When a nodelink is activated, it follows a specific discovery process:

* Is there a corrresponding certificate in the local nodelink cache. If so, use
this, if it's not expired.

* Otherwise, check the immediate peers (the immediate neighborhood) to see if a
nodelink is resolvable. This is important because not all nodelinks are public.

* If the link cannot be resolved in the immediate neighborhood, go to the public
node registries.

* If no node is found at that point of resolution, return an HSTP No Address
error (the analog to an HTTP 404 code).

Once a connection is made, the corresponding certificate is cached so that this
process of discovery doesn't need to take place again until the next TTL.

== Augmented Node Graphs

In some cases, it is possible to attach the graph of one node to another in
order to create a larger federated graph. This bypasses the normal HSTP protocol
system. This is used primarily for those cases where a single domain may in fact
be distributed across multiple servers, or where common resources such as
schemas are shared across multiple chained nodes. The chained nodes are called
__Augmenting Node Graphs__ and the chaining graph is called the __Augmented Node
Graph__. More information will be forthcoming regarding such graphs.


== Repositories, Registries

A __repository__ is a spatial web node that contains commonly utilized taxonomies, schemas, agents, activities, and other resources. A __registry__, on the other hand, is a way of registering the locations of specific spatial web nodes and their associated resources. The spatial web nodes, then would make use of the same DNS registry that HTTP and HTTPS uses, with the additional caveat that access would be moderated by credentials.

The Spatial Web Foundation should be responsible for maintaining core repositories, especially places, taxonomic concepts, activity components and schemas. This is a common requirement, and while others can and will create
their own definitions, they can use spatial web concepts to provide core
provenance and structure.

The Spatial Web Foundation should also be responsible for a Spatial Web
Registration Authority (SWRA). The purpose of such a registry is to provide a
clearinghouse for identifying and classifying public domains, using the Spatial
Web UDG Taxonomy (and the corresponding hsml:hasTopic and related predicates) to
help to identify relevant content.

When a Spatial Web Node is registered with SWRA several things happen:


* The ipv6 address of the node server is registered, along with a web domain
name and (if different from the default) a port. The SWRA registry can also
register the relevant IP addresses.

* A SW domain on a SW node can be assigned a public SWRA credential that
indicates that the domain in question is a part of the SWRA network (similar
networks can be established with different sets of credentials).

* Periodically, the spatial web node can send an update of all domains on that
node that have the relevant credentials. This include any metadata (topics) that
are associated with the domain. Note that these domains provide access points to
other domains that may not necessarily be transmitted to the registry. As such
they should be seen as starting points for various domain activities. Not all
domains on a node need (or should) be so registered.

* Registries that issue their own credentials create __affiliation networks__.
For instance, a given company that produces lines of IoT devices with associated
HSML interfaces may end up providing an affiliation network of all nodes that
make use of these devices, and as such share common domain and agent interfaces,
taxonomies, structures and so forth. Similarly, a multi-system role playing game
may set up an affiliation network where each node hosts one or more domains in
that particular universe, with the ability for agents to move from one node to
another through the use of supported credentials in that affiliation network.

* A SW Node (and associated domains) can be part of multiple affiliation
networks. For instance, a federal government may provide a core affiliation
network for its member states, each both sharing resources and providing
information, as well as identifying what other nodes are part of that
affiliation.

* Both a repository and a registry are spatial web nodes. What differentiates
them is primarily whether they have the additional functions of registration and
whether they permit sharing within one or more affiliate networks. This are
additional modules that can be added on to the base functionality of the spatial
web node.

* Moreover, a spatial web node can be both a repository and a registry.