=== UDG and HSTP

A typical Spatial Web UDG Node consists of a number of key components.

* __The hstp.d daemon.__ This is the analog to the http.d daemon that powers HTTP web servers. It handles the receipt of messages across channnels to the SW Node, and it also routes messages in outbound channels to their destination. Its primary purpose is to communicate with the broader Spatial Web, though it also has certain operations that it can perform on the underlying domain graph of the SW Node.
* __The hsml.d process.__ This interprets incoming HSML messages and translates these into specific UDG query and update commands. It is usually invoked by the hstp.d daemon to provide interpretation of HSML, but it can also be used as necessary to create HSML DOMs. In this phase, the assumption is that the incoming HSML will be in some form of RDF - JSON-LD, Turtle, RDF-XML etc, but this is not necessarily a formal requirement so long as there is some consistent mapping to the internal representation.
* __The udg.d domain daemon.__ This is an internal high frequency loop that is used in order to animate domains to manage state. It is only very peripherally connected to HSTP (primarily when dealing with SW Node to Node communication), but in general it this process that handles the internal state changes to the domain graph.
* __The domain graph.__ The domain graph is a graph that maintains state within the various domains contained within the SW Node. Collectively, the set of all domain graphs of all Spatial Web Nodes is known as the __Universal Domain Graph__ (or __UDG__). However, it is worth noting that this is not a single comprehensive graph but rather a collection of graphs.
* __augmented graph module__. This is a module that works in conjunction with the hsml.d process to join multiple domain graphs together into a single comprehensive graph. Note that this is used primarily to extend the domain graph for handling complex environments, and generally sits outside of the normal hstp.d processes.
* __certificate caches__. There are multiple certificate caches that are maintained by each Spatial Web Node in order to reduce access time, especially for permissions. The caching mechanism also serves to help resolve SWIDs on the local system.
* __SWID Generator__. Each Spatial Web node contains a mechanism to generate SWIDs that follow SWID certificate standards, in effect acting like a wallet. This may be implemented as a subgraph in the system or as a separate blockchain.
* __Transformation Pipeline__. Ordinarily, the output from a query will be some form of graph. However, for a number of reasons, there will be times when the output needs to be transformed into some other format (most especially HSML) or filtered in some other way (such as through an LLM). The transformation pipeline handles this process.
* __Collector__. Certain operations involve aggregating the results of queries across multiple spatial web nodes. The Collector module (part of hstp.d) is a queue that collects incoming messages and aggregates them for transmission back to the client. The exact details of the collector module are still TBD.
* __Extension Modules__. In all of these components, the fundamental design will be modular, such that each component can be extended by code depending upon implementation. For instance, the HSML encoder, the UDG.d and the HSTP.d all have access points for agentic systems and e-commerce capabilities, components can be used for converting external datasets into data analytics forms, transformations can be written that generate images, maps, and related formats and so forth. These module extensions would be integrated in by individual SW Node Administrators. 