= IEEE requirements mapped to UDG design spec

The table lists requirements in <<STD-1, SWF STD-1:2025 (v3.3.2) September 26, 2025 >> that are allocated to the UDG Design Specification.   The Table also includes the clause of the UDG Specificaiton where the System requirements are addressed.

.IEEE requirements mapped to UDG design spec
[cols="1a,5a,1a", options="header"]
|===
| IEEE Clause | Requirement | UDG Clause 

| 5.2.3.2.2.
| Enable discovery of virtual representations of physical entities
|

| 5.2.3.3.2.
| Enable discovery of physical and virtual entities via discovery services
|

| 6.3.3.4.
| Validate SWIDs generated using SWID Method
|

| 6.3.3.4.
| Include Spatial Web registration service
|

| 1.2.5
| Register all SWIDs in Spatial Web Registry
|

| 1.2.6
| Enable domain verification and validation
|

| 1.2.7
| Support flexible SWID generation
| link:entity-registries.md[Entity Registries]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.3.3.4]
|

| 1.2.8
| Ensure SWID uniqueness
| link:udg-swids.md[UDG SWIDs]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.3.3.4]
|

| 1.2.9
| Maintain SWIDs in Registry
| link:entity-registries.md[Entity Registries]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.3.3.4]
|

| 1.2.10
| Maintain resilient operations
| link:udg-and-hstp.md[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.3.4.9]
|

| 1.2.11
| Provide distributed operations
| link:udg-and-hstp.md[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.3.5.3]
|

| 1.2.12
| Provide seamless domain interactions
| link:udg-and-hstp.md[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.3.5.3]
|

| 1.2.13
| Implement registration processes
| link:node-registries.md[Node Registries]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.3.5.3]
|

| 1.2.14
| Enable varied access methods
| link:udg-and-hstp.md[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.3.5.3]
|

| 1.2.15
| Register and manage ACTIVITIES
| https://www.notion.so/UDG-Activities-1fc40ac3a1e88086b23bd4fe3e97d361?pvs=21[UDG Activities]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.4.4.8]
|

| 1.2.16
| Record HSML ACTIVITIES
| UDG Activities
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[6.4.4.8]
|

| 1.2.17
| Support high-performance networking
| link:udg-and-hstp.md[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.1.3]
|

| 1.2.18
| Enable automatic node discovery
| link:node-registries.md[Node Registries]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.1.3]
|

| 1.2.19
| Scale to internet level
| link:node-registries.md[Node Registries]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.1.3]
|

| 1.2.20
| Include Spatial Index Servers
| https://www.notion.so/HyperSpace-1fc40ac3a1e88073baabdb1c94038473?pvs=21[Hyperspace], link:entity_registries.md[Entity Registries]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.2.2]
|

| 1.2.21
| Manage entity updates
| https://www.notion.so/UDG-and-HSTP-1fc40ac3a1e88011aa18e39a6557dfc3?pvs=21[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.2.2]
|

| 1.2.22
| Manage rapid entity changes
| https://www.notion.so/UDG-and-HSTP-1fc40ac3a1e88011aa18e39a6557dfc3?pvs=21[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.2.2]
|

| 1.2.23
| Manage slow-changing entities
| https://www.notion.so/UDG-and-HSTP-1fc40ac3a1e88011aa18e39a6557dfc3?pvs=21[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.2.2]
|

| 1.2.24
| Handle consensus latency
| link:udg-and-hstp.md[UDG and HSTP]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.2.2]
|

| 1.2.25
| Implement specified use cases
| https://www.notion.so/UDG-and-HSTP-1fc40ac3a1e88011aa18e39a6557dfc3?pvs=21[UDG and HSTP], link:representations.md[Representations]
| https://www.notion.so/IEEE-UDG-Requirements-1fa40ac3a1e8802cbca5f503e627a391?pvs=21[7.4.2]
|

|===


STD-1 Clause	STD-1 Requirement	UDG Clause
5.2.3.2.2.
UDG shall enable discovery of the virtual representation of physical entities. 	
5.2.3.3.2.
UDG shall enable discovery of physical and virtual entities via discovery services. 	
6.3.3.4.
UDG shall validate SWIDs generated using SWID Method prior to issuance, e.g., assess uniqueness. 	
6.3.3.4.
UDG shall include a Spatial Web registration service for Public and Top domains. 	
6.3.3.4.
UDG shall, for audit purposes, register all SWIDs related to all public and top domains in a Spatial Web Registry. 	
6.3.3.4.
UDG shall enable verification and validation services for domains prior to their registration. 	
6.3.3.4.
UDG shall support the generation of SWIDs one at a time, such as for Top Domains, or generate many at a time, such as for Public Domains. 	
6.3.3.4.
UDG shall ensure SWID uniqueness. 	
6.3.3.4.
UDG shall ensure that SWIDs are maintained in the Spatial Web Registry. 	
6.3.4.9.
UDG operations shall be resilient to inconsistencies in relationships between nodes and in the content of nodes. 	
6.3.5.3.
UDG shall provide for distributed operations of the UDG including propagation of changes and consistency. 	
6.3.5.3.
UDG shall provide Spatial Web Domain interactions that are seamlessly managed and integrated. 	
6.3.5.3.
UDG shall implement Spatial Web Domain registration processes as defined in clause 6.3.6. 

6.3.5.3.
UDG design and procedures shall enable a range of methods for accessing the UDG from basic, open access to UDG access services with enhanced value in accord with economic exchange, e.g, fee, advertising, etc. 	
6.4.4.8.
UDG shall provide the capability to register and manage ACTIVITIES that are associated with AGENTs, reflecting their capabilities and permissions. 	
6.4.4.8.
UDG shall keep a record of HSML ACTIVITIES that were executed as part of a Contract, providing a history of the Activity, verification of the execution of the Activity, and enabling the tracking of the Activity’s progress. 	
7.1.3.
UDG shall be designed to operate with communication network performance where bandwidth ranging from hundreds of gigabits per second to several terabits per second (i.e., having latency in the sub-millisecond range). 	
7.1.3.
UDG shall provide mechanisms for automatic discovery of nodes, and their properties and capabilities as well as the means to access them. 	
7.1.3.
UDG shall support the ability to accommodate an increasing number of connectivity endpoints, reaching internet scale. 	
7.2.2.
UDG shall include Spatial Index Servers that make maps ranging from simple SQL indexes to graph-based databases to widely adopted and standard spatial indexing services which deliver spatial indexing. 	
7.2.2.
UDG shall manage entity replication and update with consideration of how quickly the entities are changing. 	
7.2.2.
UDG shall manage rapidly changing entities using a peer-to-peer methodology between Spatial Servers, managed by cloud instance(s), but bound by spatial CONTRACTs stored in a DLT Spatial Domain. 	
7.2.2.
UDG shall manage slow-changing cross-ledger entities and CONTRACTs on a distributed ledger. 	
7.2.2.
UDG System may incur latency when achieving consensus. 	
7.4.2.
UDG shall implement the use cases: 7.4.4, and 7.4.11. 

