# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: post all hands discussion

on:
  workflow_dispatch:

jobs:
  post_discussion:
    defaults:
      run:
        working-directory: tools/create-all-hands-discussion
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Run
        run: cargo run
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_ALL_HANDS_DISCUSSION_ACTION }}
